{{- if .Values.ingress.enabled -}}
{{- $fullName := include "nhsei-website.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "nhsei-website.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.ingress.auth }} 
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ .Values.ingress.auth.secret }}
    nginx.ingress.kubernetes.io/auth-realm: {{ .Values.ingress.auth.realm }}
  {{- end }}
spec:
  {{- if .Values.ingress.tlshosts }}
  tls:
    {{- range .Values.ingress.tlshosts }}
    - hosts:
        - {{ . | quote }}
      secretName: tls-secret-{{ . | replace "." "_" }}
    {{- end }}
  {{- end }}
  rules:
    - host: www.england.nhs.uk
      http:
        paths:
        - path: /(.*)
          backend:
            serviceName: {{ $fullName }}
            servicePort: {{ $svcPort }}
    {{- range .Values.ingress.hostnames }}
    - host: {{ . | quote }}
      http:
        paths:
        - path: /(.*)
          backend:
            serviceName: {{ $fullName }}
            servicePort: {{ $svcPort }}
    {{- end }}
  {{- end }}
